### ISSUE TITLE
How can HL modules use Titanium APIs like classic modules have?

### ISSUE THREAD

**Issue by FokkeZB** [hansemannn/hyperloop-module-template#4]
I'm not very familiar with how classic modules work, but I think we have a set of [APIs](http://docs.appcelerator.com/platform/latest/#!/guide/Titanium_Mobile_Module_API) to hook into things right?

The HL modules will need these as well. But frankly, as I pointed out in #3 HL modules should be nothing more then packaged CommonJS files, which means these utilities would be available anywhere in your app via `Ti.*` namespace objects.

**Comment by hansemannn** [comment]
Part of [this epic](https://jira.appcelerator.org/browse/TIMOB-20416) -> https://jira.appcelerator.org/browse/TIMOB-20417

**Comment by yuchi** [comment]
My two cents: standard stuff from titanium should be accessed through explicit requires, not through magic namespaces.

``` js
// from
Ti.UI.createView({ });
// to
import { View } from 'titanium/ui/common';
// or
import View from 'titanium/ui/common/view';
```

**Comment by FokkeZB** [comment]
Indeed @yuchi and from what I heard from @hansemannn that will be the case.

**Comment by hansemannn** [comment]
Hey, we will move from namespacing to require-statements.

**Comment by yuchi** [comment]
Really?! Awesome!!!

**Comment by hansemannn** [comment]
Update on this: We will, but not in the 5.4.0 timeframe (more likely for 6.0.0). Anyway, closing this Github issue with reference to the JIRA ticket above. Thanks guys!
